

// the model is the data of our app
// the data we need:
//   - address of dwane.co brain
//   - uid (from the user)
//   - cid (generated by the server using token or info from client computer)
//   - external IP address of computer


function Model() {
    console.log('model creating');
    
    var that = this;
    this.load_(function(data) {
    // if we have a saved model, load it, otherwise use defaults
        if (data) {
            console.log('loaded dta');
            this.brain = data.brain;
            this.uid = 'herro'; //data.uid;
            this.cid = data.cid;
            this.ips = data.ips;
            that.onChange.call(that, this);
            
        } else { 
            console.log('setting default dta');
            this.brain = "http://dwane.co";
            this.uid = 'default';
            this.cid = '';
            this.ips = [];
            this.save_();
        }
    });
};

/**
 * save to the storage
 */
Model.prototype.save_ = function save_(data) {
    chrome.storage.local.set(data, function() {
        // Notify that we saved.
        console.log('Settings saved');
        console.dir(this);
    });
}

/**
 * Loads data from chrome local storage.
 *
 * @callback onLoaded (object items)
 */
Model.prototype.load_ = function load_(onLoaded) {
    //var that = this;
    chrome.storage.local.get(null, onLoaded) //function(items) {
 //       console.log('items got: ' + items);
 //       console.dir(items);
 //       that.onChange.call(this, items);
 //   });
}